#!/bin/bash
Consertive_Mode=$(cat /sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode)
case "$Consertive_Mode" in
    0)
        echo 1 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode
        notify-send "Conservation Mode Enable"
        ;;
    1)
        echo 0 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode
        notify-send "Conservation Mode Disable"
        ;;
esac