#!/bin/bash
#ADD TO HYPERLAND CONFIG: exec = $HOME/.config/hypr/set-displays-swayidle set_res

set -ex

##Starter Commands
laptop_igpu=eDP-2
laptop_dgpu=eDP-1
external_display=HDMI-A-1
laptop_ori=0x0
external_display_ori=1920x0
hyprctl -j monitors | grep -F -q $external_display && EXT_MONITOR=1 || EXT_MONITOR=0
POWER_ADAPTER=$(cat /sys/class/power_supply/ADP0/online)

#Set Refresh Rate & Time Values
[ $POWER_ADAPTER -eq 1 ] && refresh_rate="165hz" && time_1=300 && time_2=310 && time_3=600 || refresh_rate="96.012hz" && time_1=270 && time_2=280 && time_3=300

main() {
  #Verify if swayidle is running
  killall swayidle || true

  swww img "/home/mrduarte/Pictures/Lenovo Wallpapers/cyber_box.jpg" || true

	#Set display
  hyprctl keyword monitor $laptop_igpu,1920x1080@$refresh_rate,$laptop_ori,1,bitdepth,10,vrr,1
  hyprctl keyword monitor $laptop_dgpu,1920x1080@$refresh_rate,$laptop_ori,1,bitdepth,10,vrr,1
	hyprctl keyword monitor $external_display,preferred,$external_display_ori,1,bitdepth,10,vrr,1

  #Set Swayidle For Suspend
  ## GTKLock command
  swayidle \
	  timeout $time_1 'hyprctl dispatch dpms off' \
    timeout $time_2 'lock' \
	  resume 'hyprctl dispatch dpms on' \
	  timeout $time_3 '$HOME/.config/hypr/set-displays-swayidle verify_player' \
	  before-sleep 'lock' &
}

case "$1" in
lid_close)
	[[ $EXT_MONITOR -eq 1 ]] && hyprctl keyword monitor "${laptop_igpu}, disable" && hyprctl keyword monitor "${laptop_dgpu}, disable"  || systemctl suspend
	;;
lid_open)
	[[ $EXT_MONITOR -eq 1 ]] && hyprctl keyword monitor ${laptop_igpu},1920x1080@${refresh_rate},${laptop_ori},1,bitdepth,10,vrr,1 && hyprctl keyword monitor ${laptop_dgpu},1920x1080@${refresh_rate},${laptop_ori},1,bitdepth,10,vrr,1, || true
	;;
verify_player)
	[[ $(playerctl status) == "Playing" ]] && hyprctl dispatch dpms off || systemctl suspend
	;;
set_res)
	[[ $EXT_MONITOR -eq 1 ]] && hyprctl keyword monitor $external_display,preferred,$external_display_ori,1 || hyprctl keyword monitor $laptop,1920x1080@$refresh_rate,$e_DP1_ori,1,bitdepth,10
	;;
*)
  main
	;;
esac
